function [fitresult, gof] = createFitAx(axZ, axGNTV)
%CREATEFIT(AXZ,AXGNTV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: axZ
%      Y Output: axGNTV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Apr-2025 11:57:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( axZ, axGNTV );

% Set up fittype and options.
ft = fittype( '(b1-b2)/(1+exp((x1-x)/l1))/(1+exp((x-x2)/l2))+b2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [10 4 0.01 0.01 1 2.5];
opts.StartPoint = [0.837803183078576 0.739072227273528 0.954174456379543 0.756509543501944 0.0319226295039784 0.356868986182542];
opts.Upper = [14 8 0.4 0.4 2 4];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'axGNTV vs. axZ', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'axZ', 'Interpreter', 'none' );
ylabel( 'axGNTV', 'Interpreter', 'none' );
grid on


