function [fitresult, gof] = createFitLat(lat, latGNTV)
%CREATEFIT(LAT,LATGNTV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: lat
%      Y Output: latGNTV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Apr-2025 12:00:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( lat, latGNTV );

% Set up fittype and options.
ft = fittype( '(b1-b2)/(1+exp((x1-x)/l1))/(1+exp((x-x2)/l2))+b2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [10 4 0.01 0.01 -1.5 0.5];
opts.StartPoint = [0.660437966312602 0.0475546731138661 0.348784808510059 0.451340580355743 0.240904997120111 0.715045013296177];
opts.Upper = [14 Inf 0.5 0.5 0.5 1.5];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'latGNTV vs. lat', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'lat', 'Interpreter', 'none' );
ylabel( 'latGNTV', 'Interpreter', 'none' );
grid on


